version: '3.8'

services:
  frontend:
    build: ./src/vista/frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - geobizi-net

  backend:
    build: ./src/controlador
    ports:
      - "5000:5000"
    volumes:
      - ./src/modelo:/app/modelo
    depends_on:
      - db
    networks:
      - geobizi-net

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - geobizi-net
    # Para SQLite, puedes omitir este servicio y usar un volumen compartido

networks:
  geobizi-net:
    driver: bridge

# Instrucciones para arrancar el entorno Docker:

# 1. Abre una terminal y navega a la carpeta raíz del proyecto:
#    cd c:\Users\Geobizi\Desktop\Programacion\GeobizIA\GoffardSevillanoAintzane

# 2. Ejecuta el siguiente comando para construir y arrancar todos los servicios:
#    docker-compose up --build

# 3. Para detener los contenedores, pulsa Ctrl+C en la terminal o ejecuta:
#    docker-compose down

# 4. Accede a la aplicación:
#    - Frontend: http://localhost:8080
#    - Backend: http://localhost:5000 (si tienes endpoints expuestos)
#    - Base de datos SQL Server: puerto 1433 (conéctate usando un cliente SQL)
