# Imagen base de Node.js
FROM node:18-alpine

# Directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto de desarrollo de Vue CLI
EXPOSE 8080

# Comando por defecto para desarrollo
CMD ["npm", "run", "serve"]